[package]
name = "azac"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
inquire = "0.9.1"
directories = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
